image_width: 1280
image_height: 720
camera_name: table-2-camera
camera_matrix:
  rows: 3
  cols: 3
  data: [924.24365,   0.     , 649.87042,
           0.     , 922.33788, 385.42304,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.005610, -0.095702, 0.005952, 0.002699, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [903.97131,   0.     , 654.51341,   0.     ,
           0.     , 918.93799, 387.7382 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
